language: rust
os:
  - linux
  - osx
env:
  OUTPUT_FILE = ${TRAVIS_OS_NAME}_janfeb
before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install freetype ; fi
script:
  - cargo test --verbose --release -- --nocapture
  - cargo build --release --verbose
before_deploy:
  - cd target/release
  - mv janfeb $OUTPUT_FILE
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "./target/release/${OUTPUT_FILE}"
  skip_cleanup: true
  on:
    tags: true
  