language: rust
os:
  - linux
  - osx
before_script:
  - if [ "$TRAVIS_OS_NAME" =   "osx" ]; then brew install freetype ; fi
script:
  - cargo test --verbose --release -- --nocapture
  - cargo build --release --verbose