install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host x86_64-pc-windows-msvc --default-toolchain stable -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

build_script:
  - cargo build --release
  - mkdir output
  - copy target\release\janfeb.exe output
  - robocopy assets output/assets /s /e

test_script:
  - cargo test --verbose --release -- --nocapture

artifacts:
  - path: 
    name: janfeb.zip